baseURL = "https://evtuhovich.ru/"
languageCode ="ru-ru" 
title = "Блог Ивана Евтуховича"
theme = "ananke"
googleAnalytics = ""
DefaultContentLanguage = "ru"
SectionPagesMenu = "main"
Paginate = 12
enableRobotsTXT = true

[services]
  [services.disqus]
    shortname = "blog-evtuhovich"

[markup.goldmark.renderer]
unsafe = true

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1

[params]
  favicon = "/images/favicon.ico"
  description = "Блог Ивана Евтуховича"
  # facebook = "https://www.facebook.com/evtuhovich"
  github = "https://github.com/evtuhovich/"
  # twitter = "https://twitter.com/evtuhovich"
  # instagram = "https://www.instagram.com/evtuhovich/"
  featured_image = "/images/background.jpg"
  recent_posts_number = 10
  mainSections = ["blog", "life"]
  custom_css = ["css/custom.css"]
  recent_copy = "Недавние записи"
  ananke_socials = [
    { name = "vk", url = "https://vk.com/ivan.evtuhovich" },
    { name = "telegram", url = "https://t.me/evtuhovich" }
  ]

[[deployment.targets]]
# An arbitrary name for this target.
name = "s3"
# The Go Cloud Development Kit URL to deploy to. Examples:
# GCS; see https://gocloud.dev/howto/blob/#gcs
# URL = "gs://<Bucket Name>"

# S3; see https://gocloud.dev/howto/blob/#s3
# For S3-compatible endpoints, see https://gocloud.dev/howto/blob/#s3-compatible
URL = "s3://evtuhovich.ru?region=eu-west-1"

# Azure Blob Storage; see https://gocloud.dev/howto/blob/#azure
# URL = "azblob://$web"

# You can use a "prefix=" query parameter to target a subfolder of the bucket:
# URL = "gs://<Bucket Name>?prefix=a/subfolder/"

# If you are using a CloudFront CDN, deploy will invalidate the cache as needed.
# cloudFrontDistributionID = <ID>

# Optionally, you can include or exclude specific files.
# See https://godoc.org/github.com/gobwas/glob#Glob for the glob pattern syntax.
# If non-empty, the pattern is matched against the local path.
# All paths are matched against in their filepath.ToSlash form.
# If exclude is non-empty, and a local or remote file's path matches it, that file is not synced.
# If include is non-empty, and a local or remote file's path does not match it, that file is not synced.
# As a result, local files that don't pass the include/exclude filters are not uploaded to remote,
# and remote files that don't pass the include/exclude filters are not deleted.
# include = "**.html" # would only include files with ".html" suffix
# exclude = "**.{jpg, png}" # would exclude files with ".jpg" or ".png" suffix


# [[deployment.matchers]] configure behavior for files that match the Pattern.
# Samples:
