baseURL = "http://evtuhovich.ru/"
languageCode ="ru-ru" 
title = "Блог Ивана Евтуховича"
theme = "ananke"

DefaultContentLanguage = "ru"
SectionPagesMenu = "main"
Paginate = 12
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = "https://www.facebook.com/evtuhovich"
  twitter = "https://twitter.com/evtuhovich"
  instagram = "https://www.instagram.com/evtuhovich/"
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2
